# Generated by Django 5.1.6 on 2025-02-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('established', models.PositiveIntegerField()),
                ('countryOfOrigin', models.CharField(max_length=255)),
                ('defunct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CarSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
                ('displacement', models.FloatField()),
                ('power', models.PositiveIntegerField()),
                ('kilometrageCity', models.FloatField()),
                ('kilometrageRoad', models.FloatField()),
                ('weight', models.PositiveIntegerField()),
                ('top_speed', models.PositiveIntegerField()),
                ('zero_to_hundred', models.FloatField()),
                ('categories', models.ManyToManyField(to='AplikaceUkol.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplikaceUkol.manufacturer')),
            ],
        ),
    ]
