# Generated by Django 5.1.7 on 2025-04-03 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikaceUkol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
                ('displacement', models.FloatField()),
                ('power', models.PositiveIntegerField()),
                ('kilometrageCity', models.FloatField()),
                ('kilometrageRoad', models.FloatField()),
                ('categories', models.ManyToManyField(to='AplikaceUkol.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplikaceUkol.manufacturer')),
            ],
        ),
        migrations.DeleteModel(
            name='CarSpecifications',
        ),
    ]
